// <auto-generated />
using IdentityBased.AuthServer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IdentityBased.AuthServer.Migrations
{
    [DbContext(typeof(CustomDbContext))]
    [Migration("20220116194001_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IdentityBased.AuthServer.Models.CustomUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("customUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Ankara",
                            Email = "mtunahanyollar@gmail.com",
                            Password = "password",
                            UserName = "tunahanyollar"
                        },
                        new
                        {
                            Id = 2,
                            City = "Istanbul",
                            Email = "mty@gmail.com",
                            Password = "password2",
                            UserName = "tunahanyollar2"
                        },
                        new
                        {
                            Id = 3,
                            City = "Munich",
                            Email = "testmail@gmail.com",
                            Password = "password3",
                            UserName = "tunahanyollar3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
